  general:
  log_level: INFO
  test_run: true
  timer: 10
  # ignored_download_clients: ["emulerr"]
  # ssl_verification: false # Optional: Defaults to true
  # private_tracker_handling: "obsolete_tag" # remove, skip, obsolete_tag. Optional. Default: remove
  # public_tracker_handling: "remove"  # remove, skip, obsolete_tag. Optional. Default: remove
  # obsolete_tag: "Obsolete" # optional. Default: "Obsolete"
  # protected_tag: "Keep" # optional. Default: "Keep"

job_defaults:
  max_strikes: 3
  min_days_between_searches: 7
  max_concurrent_searches: 3

jobs:
  remove_bad_files:
    # keep_archives: true
  remove_done_seeding:
    # target_tags:
    #   - "Obsolete"
    # target_categories:
    #  - "autobrr"
  remove_failed_downloads:
  remove_failed_imports:
    message_patterns:
      - "Not a Custom Format upgrade for existing*"
      - "Not an upgrade for existing*"
      - "*Found potentially dangerous file with extension*"
      - "Invalid video file*"
      - "No files found are eligible for import*"
      - "One or more episodes expected in this release were not imported or missing from the release"
  remove_metadata_missing:
    # max_strikes: 3
  remove_missing_files:
  remove_orphans:
  remove_slow:
    # min_speed: 100
    # max_strikes: 3
  remove_stalled:
    # max_strikes: 3
  remove_unmonitored:
  search_unmet_cutoff:
    # min_days_between_searches: 7
    # max_concurrent_searches: 3
  search_missing:
    # min_days_between_searches: 7
    # max_concurrent_searches: 3

instances:
  sonarr:
    - base_url: "https://series.lacny.me"
      api_key: !ENV SONARR_API_KEY
  radarr:
    - base_url: "https://movies.lacny.me"
      api_key: !ENV RADARR_API_KEY

download_clients:
  qbittorrent:
    - base_url: "https://qbittorrent.lacny.me" # You can use decluttarr without qbit (not all features available, see readme).
      username: admin # (optional -> if not provided, assuming not needed)
      password: !ENV QBITTORRENT_PASSWORD # (optional -> if not provided, assuming not needed)
      # name: "qBittorrent" # (optional -> if not provided, assuming "qBittorrent". Must correspond with what is specified in your *arr as download client name)
  # sabnzbd:
  #   - base_url: "http://sabnzbd:8080" # SABnzbd server URL
  #     api_key: "your_api_key_here" # (required -> SABnzbd API key)
  #     # name: "SABnzbd" # (optional -> if not provided, assuming "SABnzbd". Must correspond with what is specified in your *arr as download client name)