services:
  frigate:
    container_name: surveillance-frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.16.1
    shm_size: "580mb" # update for your cameras based on calculation above
    devices:
      - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      - /dev/dri/renderD128 
      - /dev/dri
      - /dev/kfd
    volumes:
      - /root/surveillance/frigate:/config # config.yml location
      # - /mnt/frigate:/media/frigate # NAS - remote
      - /mnt/frigate-local:/media/frigate # local HDD
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      - FRIGATE_GEMINI_API_KEY=${FRIGATE_GEMINI_API_KEY}
      - FRIGATE_RTSP_CREDENTIALS=${FRIGATE_RTSP_CREDENTIALS}
      - FRIGATE_MQTT_USER=${FRIGATE_MQTT_USER}
      - FRIGATE_MQTT_PASSWORD=${FRIGATE_MQTT_PASSWORD}
      - TZ=Europe/Bratislava
      - LIBVA_DRIVER_NAME=radeonsi
    # healthcheck:
    #   test: curl --fail http://localhost:5000/api/version || exit 1
    #   interval: 30s
    #   retries: 3
    #   start_period: 30s
    #   timeout: 1s
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://frigate:5011/api/stats"]
    #   interval: 1m
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s    
    labels:
      autoheal: true
      caddy: http://frigate.lan, frigate.lacny.me
      caddy.reverse_proxy: "{{ upstreams 5000 }}"
    ports:
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
      - "8971:8971" # New restricted access port in >= v14.0     
      - "5011:5000"
      - "1984:1984"
      
  scheduled-restarts:
    image: docker:cli
    restart: unless-stopped
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        while true; do
          if [ "$$(date +'%H:%M')" = '02:00' ]; then
            docker restart surveillance-frigate
          fi
          sleep 60
        done

  # rtsp-camera:
  #   container_name: rtsp-camera
  #   image: kerberos/virtual-rtsp:1.0.6
  #   volumes:
  #     - /mnt/frigate/recordings:/recordings # NAS - remote
  #   ports:
  #     - "554:8554"
  #   environment:
  #     - SOURCE_URL=file:///recordings/2025-03-24/14/garaz-von/30.09.mp4 

